repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.56.0
          - xo@0.57.0
        files: \.[mc]?[tj]sx?$
        types: [file]
