repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - xo
        files: \.[mc]?[tj]sx?$
        types: [file]
